### ISSUE TITLE
Pandas error not installing 

### ISSUE THREAD

**Issue by Deepak960085** [smzerehpoush/binance-spot-trading-bot#4]
Traceback (most recent call last):
File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/main.py", line 9, in
from indicators import rsi_fourteen_days_close, rsi_fifteen_days_close, heikin_today, heikin_yesterday,
File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/indicators.py", line 3, in
from heikin_ashi import calculate_heikin_ashi
File "/storage/emulated/0/Download/binance-spot-trading-bot-mainmmm/binance-spot-trading-bot-main/heikin_ashi.py", line 3, in
import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by smzerehpoush** [comment]
did you run `pip install -r requirements.txt`
